In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.dualemb import DualEmbPredictor

In [2]:
ITERATIONS = 1
random.seed(5438)
np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [5]:
model = DualEmbPredictor(num_epochs=100)

In [6]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]]

In [ ]:
model.fit(X, y, validation_set=0.2)

Epoch 1/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 573.68it/s, loss=2.1528]


Validation Loss: 1.8704
Epoch 2/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 525.86it/s, loss=2.2816]


Validation Loss: 1.7447
Epoch 3/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 510.34it/s, loss=2.2946]


Validation Loss: 1.6946
Epoch 4/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 506.45it/s, loss=2.2858]


Validation Loss: 1.6708
Epoch 5/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:05<00:00, 614.57it/s, loss=2.2787]


Validation Loss: 1.6558
Epoch 6/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 474.22it/s, loss=2.2753]


Validation Loss: 1.6453
Epoch 7/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 478.23it/s, loss=2.2416]


Validation Loss: 1.6375
Epoch 8/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 505.05it/s, loss=2.2061]


Validation Loss: 1.6319
Epoch 9/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 545.94it/s, loss=2.1967]


Validation Loss: 1.6277
Epoch 10/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 476.32it/s, loss=2.1771]


Validation Loss: 1.6244
Epoch 11/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 465.08it/s, loss=2.1594]


Validation Loss: 1.6217
Epoch 12/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 515.37it/s, loss=2.1520]


Validation Loss: 1.6194
Epoch 13/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 387.21it/s, loss=2.1477]


Validation Loss: 1.6173
Epoch 14/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 360.79it/s, loss=2.1394]


Validation Loss: 1.6155
Epoch 15/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 365.25it/s, loss=2.1256]


Validation Loss: 1.6137
Epoch 16/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 368.03it/s, loss=2.1127]


Validation Loss: 1.6122
Epoch 17/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 403.90it/s, loss=2.1052]


Validation Loss: 1.6109
Epoch 18/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 386.76it/s, loss=2.0986]


Validation Loss: 1.6098
Epoch 19/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 478.12it/s, loss=2.0894]


Validation Loss: 1.6087
Epoch 20/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 485.48it/s, loss=2.0861]


Validation Loss: 1.6079
Epoch 21/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 433.87it/s, loss=2.0780]


Validation Loss: 1.6070
Epoch 22/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 408.43it/s, loss=2.0782]


Validation Loss: 1.6061
Epoch 23/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 376.70it/s, loss=2.0771]


Validation Loss: 1.6054
Epoch 24/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 437.03it/s, loss=2.0673]


Validation Loss: 1.6047
Epoch 25/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 414.41it/s, loss=2.0618]


Validation Loss: 1.6041
Epoch 26/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 414.59it/s, loss=2.0621]


Validation Loss: 1.6037
Epoch 27/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 383.56it/s, loss=2.0582]


Validation Loss: 1.6031
Epoch 28/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 412.92it/s, loss=2.0525]


Validation Loss: 1.6029
Epoch 29/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 390.70it/s, loss=2.0542]


Validation Loss: 1.6024
Epoch 30/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 430.76it/s, loss=2.0505]


Validation Loss: 1.6020
Epoch 31/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 445.05it/s, loss=2.0461]


Validation Loss: 1.6018
Epoch 32/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:10<00:00, 340.62it/s, loss=2.0359]


Validation Loss: 1.6015
Epoch 33/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 390.41it/s, loss=2.0314]


Validation Loss: 1.6013
Epoch 34/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 448.54it/s, loss=2.0193]


Validation Loss: 1.6012
Epoch 35/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 490.28it/s, loss=2.0193]


Validation Loss: 1.6011
Epoch 36/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 488.69it/s, loss=2.0245]


Validation Loss: 1.6009
Epoch 37/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 455.28it/s, loss=2.0228]


Validation Loss: 1.6007
Epoch 38/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 477.22it/s, loss=2.0256]


Validation Loss: 1.6004
Epoch 39/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 554.40it/s, loss=2.0228]


Validation Loss: 1.6003
Epoch 40/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 461.73it/s, loss=2.0213]


Validation Loss: 1.6003
Epoch 41/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 465.30it/s, loss=2.0207]


Validation Loss: 1.6001
Epoch 42/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 478.64it/s, loss=2.0161]


Validation Loss: 1.6001
Epoch 43/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 579.43it/s, loss=2.0209]


Validation Loss: 1.6001
Epoch 44/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 485.87it/s, loss=2.0149]


Validation Loss: 1.6001
Epoch 45/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 491.39it/s, loss=2.0093]


Validation Loss: 1.6000
Epoch 46/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 477.51it/s, loss=2.0133]


Validation Loss: 1.5998
Epoch 47/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 557.42it/s, loss=2.0134]


Validation Loss: 1.5998
Epoch 48/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 482.43it/s, loss=2.0109]


Validation Loss: 1.5998
Epoch 49/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 448.32it/s, loss=2.0148]


Validation Loss: 1.5996
Epoch 50/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 462.02it/s, loss=2.0143]


Validation Loss: 1.5996
Epoch 51/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 496.09it/s, loss=2.0144]


Validation Loss: 1.5996
Epoch 52/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 367.52it/s, loss=2.0145]


Validation Loss: 1.5996
Epoch 53/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 363.18it/s, loss=2.0145]


Validation Loss: 1.5994
Epoch 54/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 452.98it/s, loss=2.0103]


Validation Loss: 1.5993
Epoch 55/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 569.39it/s, loss=2.0110]


Validation Loss: 1.5993
Epoch 56/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 472.11it/s, loss=2.0058]


Validation Loss: 1.5993
Epoch 57/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 476.32it/s, loss=2.0063]


Validation Loss: 1.5992
Epoch 58/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 479.21it/s, loss=2.0044]


Validation Loss: 1.5992
Epoch 59/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 583.46it/s, loss=2.0014]


Validation Loss: 1.5991
Epoch 60/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 487.76it/s, loss=2.0039]


Validation Loss: 1.5990
Epoch 61/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 459.26it/s, loss=2.0008]


Validation Loss: 1.5990
Epoch 62/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 429.43it/s, loss=2.0060]


Validation Loss: 1.5990
Epoch 63/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 505.46it/s, loss=2.0041]


Validation Loss: 1.5990
Epoch 64/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 423.78it/s, loss=2.0043]


Validation Loss: 1.5989
Epoch 65/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 451.12it/s, loss=2.0019]


Validation Loss: 1.5990
Epoch 66/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 430.03it/s, loss=2.0020]


Validation Loss: 1.5989
Epoch 67/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 531.37it/s, loss=2.0045]


Validation Loss: 1.5990
Epoch 68/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 463.25it/s, loss=2.0042]


Validation Loss: 1.5990
Epoch 69/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 433.07it/s, loss=2.0009]


Validation Loss: 1.5991
Epoch 70/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 446.73it/s, loss=2.0082]


Validation Loss: 1.5990
Epoch 71/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 538.71it/s, loss=2.0042]


Validation Loss: 1.5991
Epoch 72/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 473.99it/s, loss=2.0017]


Validation Loss: 1.5991
Epoch 73/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 486.04it/s, loss=2.0021]


Validation Loss: 1.5991
Epoch 74/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 472.49it/s, loss=2.0004]


Validation Loss: 1.5991
Epoch 75/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 481.10it/s, loss=1.9989]


Validation Loss: 1.5991
Epoch 76/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 560.15it/s, loss=1.9959]


Validation Loss: 1.5991
Epoch 77/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 470.18it/s, loss=1.9941]


Validation Loss: 1.5991
Epoch 78/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 460.33it/s, loss=1.9938]


Validation Loss: 1.5992
Epoch 79/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:07<00:00, 456.78it/s, loss=1.9930]


Validation Loss: 1.5991
Epoch 80/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 538.04it/s, loss=1.9952]


Validation Loss: 1.5991
Epoch 81/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 384.23it/s, loss=1.9946]


Validation Loss: 1.5992
Epoch 82/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 374.19it/s, loss=1.9926]


Validation Loss: 1.5992
Epoch 83/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 400.44it/s, loss=1.9938]


Validation Loss: 1.5993
Epoch 84/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:10<00:00, 350.61it/s, loss=1.9937]


Validation Loss: 1.5993
Epoch 85/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:09<00:00, 359.77it/s, loss=1.9916]


Validation Loss: 1.5994
Epoch 86/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:08<00:00, 402.80it/s, loss=1.9894]


Validation Loss: 1.5995
Epoch 87/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3576/3576 [00:06<00:00, 556.87it/s, loss=1.9872]


Validation Loss: 1.5995
Epoch 88/100


 36%|█████████████████████████████████████████████████████████████████▋                                                                                                                    | 1290/3576 [00:02<00:05, 441.47it/s, loss=2.0090]

In [ ]:
model.logit.model.predict(
    model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 0.0}])
)

In [38]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

NameError: name 'elo' is not defined

In [12]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.40166393, 0.28372598, 0.31461009]])

In [13]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35695543, 0.28608557, 0.356959  ]])

In [14]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 1.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.42654169, 0.28053235, 0.29292596]])

In [15]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 1.0,
            },
        ]
    )
)

array([[0.29292273, 0.28053177, 0.4265455 ]])

In [16]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.92678624, 0.04944971, 0.02376405]])

In [17]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.92678624, 0.04944971, 0.02376405]])