In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.dualemb import DualEmbPredictor

In [2]:
ITERATIONS = 1
random.seed(5438)
np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [14]:
model = DualEmbPredictor(embedding_dim=20, train_learning_rate=0.001, num_epochs=50)

In [15]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]] / 10.0

In [ ]:
model.fit(X, y, validation_set=0.1)

Epoch 1/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:14<00:00, 270.46it/s, loss=0.0184]


Validation Loss: 0.0185
Epoch 2/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:15<00:00, 268.04it/s, loss=0.0158]


Validation Loss: 0.0172
Epoch 3/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 381.97it/s, loss=0.0155]


Validation Loss: 0.0166
Epoch 4/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 307.19it/s, loss=0.0158]


Validation Loss: 0.0164
Epoch 5/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 332.51it/s, loss=0.0157]


Validation Loss: 0.0163
Epoch 6/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 324.51it/s, loss=0.0157]


Validation Loss: 0.0162
Epoch 7/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 317.14it/s, loss=0.0158]


Validation Loss: 0.0162
Epoch 8/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 325.07it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 9/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 294.84it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 10/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 298.07it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 11/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 324.97it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 12/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 304.45it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 13/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:15<00:00, 258.88it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 14/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:14<00:00, 268.40it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 15/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:15<00:00, 258.40it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 16/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:14<00:00, 268.89it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 17/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 195.99it/s, loss=0.0157]


Validation Loss: 0.0161
Epoch 18/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 173.11it/s, loss=0.0156]


Validation Loss: 0.0161
Epoch 19/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 169.11it/s, loss=0.0155]


Validation Loss: 0.0161
Epoch 20/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 209.72it/s, loss=0.0155]


Validation Loss: 0.0161
Epoch 21/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 187.30it/s, loss=0.0153]


Validation Loss: 0.0161
Epoch 22/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 199.59it/s, loss=0.0152]


Validation Loss: 0.0161
Epoch 23/50


 60%|███████████████████████████████████████▎                         | 2430/4022 [00:14<00:09, 167.72it/s, loss=0.0130]

In [22]:
model.logit.model.predict(
    model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 0.0}])
)

array([[0.35364622, 0.29270742, 0.35364636]])

In [23]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35364622, 0.29270742, 0.35364636]])

In [24]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35364622, 0.29270742, 0.35364636]])

In [11]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35364622, 0.29270742, 0.35364636]])

In [12]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 1.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.47473848, 0.27645116, 0.24881036]])

In [13]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 1.0,
            },
        ]
    )
)

array([[0.24881024, 0.27645112, 0.47473863]])

In [14]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": str(random.random()),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35364622, 0.29270742, 0.35364636]])

In [15]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": str(random.random()),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35364622, 0.29270742, 0.35364636]])

In [16]:
model.predict_and_update(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    ),
    pd.DataFrame(
        [
            {
                "team_score": 4,
                "opponent_score": 0,
            },
        ]
    ),
)

array([[0.35364622, 0.29270742, 0.35364636]])

In [17]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.37110828, 0.2923255 , 0.33656622]])

In [18]:
model.embeddings

{'Argentina': [-0.08893371373414993,
  -0.0035135094076395035,
  0.1328645944595337,
  0.05630768463015556,
  -0.11929374188184738,
  -0.059678755700588226,
  0.03489013761281967,
  0.05197321996092796,
  -0.150115504860878,
  -0.05653221532702446],
 'Brazil': [-0.06893371790647507,
  0.016486484557390213,
  0.11286459863185883,
  0.0363076888024807,
  -0.13929373025894165,
  -0.03967875987291336,
  0.014890139922499657,
  0.07197321206331253,
  -0.13011550903320312,
  -0.036532219499349594]}

In [19]:
model.predict_and_update(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    ),
    pd.DataFrame(
        [
            {
                "team_score": 0,
                "opponent_score": 10,
            },
        ]
    ),
)

array([[0.37110828, 0.2923255 , 0.33656622]])

In [20]:
model.embeddings

{'Argentina': [-0.0789337158203125,
  0.006486488506197929,
  0.12286459654569626,
  0.04630768671631813,
  -0.12929373979568481,
  -0.04967875778675079,
  0.02489013969898224,
  0.061973217874765396,
  -0.14011549949645996,
  -0.04653221741318703],
 'Brazil': [-0.0789337158203125,
  0.0064864857122302055,
  0.12286459654569626,
  0.04630769044160843,
  -0.12929372489452362,
  -0.04967875778675079,
  0.02489013969898224,
  0.0619732141494751,
  -0.14011551439762115,
  -0.04653221741318703]}

In [21]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35364622, 0.29270742, 0.35364636]])