In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.dualemb import DualEmbPredictor

In [2]:
ITERATIONS = 1
random.seed(5438)
np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [5]:
model = DualEmbPredictor(num_epochs=20)

In [6]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]]

In [8]:
model.fit(X, y, validation_set=0.1)

num_samples 143005
Epoch 1/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 146.26it/s, loss=1.5298]


Validation Loss: 1.8054
Epoch 2/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:31<00:00, 128.19it/s, loss=1.4794]


Validation Loss: 1.6753
Epoch 3/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:38<00:00, 104.40it/s, loss=1.4608]


Validation Loss: 1.6379
Epoch 4/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:35<00:00, 112.52it/s, loss=1.4532]


Validation Loss: 1.6204
Epoch 5/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 150.36it/s, loss=1.4461]


Validation Loss: 1.6092
Epoch 6/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 165.37it/s, loss=1.4505]


Validation Loss: 1.6014
Epoch 7/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 186.18it/s, loss=1.4561]


Validation Loss: 1.5956
Epoch 8/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 183.37it/s, loss=1.4522]


Validation Loss: 1.5916
Epoch 9/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 171.66it/s, loss=1.4500]


Validation Loss: 1.5882
Epoch 10/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:29<00:00, 137.20it/s, loss=1.4459]


Validation Loss: 1.5853
Epoch 11/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 142.92it/s, loss=1.4405]


Validation Loss: 1.5828
Epoch 12/20


100%|███████████████████████████████████████████████████████████████████████████████████| 4022/4022 [05:48<00:00, 11.54it/s, loss=1.4320]


Validation Loss: 1.5805
Epoch 13/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 138.94it/s, loss=1.4244]


Validation Loss: 1.5786
Epoch 14/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:31<00:00, 127.07it/s, loss=1.4212]


Validation Loss: 1.5769
Epoch 15/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 165.39it/s, loss=1.4159]


Validation Loss: 1.5753
Epoch 16/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 202.59it/s, loss=1.4129]


Validation Loss: 1.5740
Epoch 17/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:25<00:00, 155.51it/s, loss=1.4122]


Validation Loss: 1.5728
Epoch 18/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 153.70it/s, loss=1.4131]


Validation Loss: 1.5718
Epoch 19/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:25<00:00, 154.84it/s, loss=1.4115]


Validation Loss: 1.5707
Epoch 20/20


100%|██████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 169.24it/s, loss=1.4127]


Validation Loss: 1.5698


In [9]:
model.logit.model.predict(model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 0.0}]))

array([[0.35370627, 0.29175984, 0.35453388]])

In [38]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

NameError: name 'elo' is not defined

In [12]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.40166393, 0.28372598, 0.31461009]])

In [13]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35695543, 0.28608557, 0.356959  ]])

In [14]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 1.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.42654169, 0.28053235, 0.29292596]])

In [15]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 1.0,
            },
        ]
    )
)

array([[0.29292273, 0.28053177, 0.4265455 ]])

In [16]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.92678624, 0.04944971, 0.02376405]])

In [17]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.92678624, 0.04944971, 0.02376405]])