In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.dualemb import DualEmbPredictor

In [2]:
ITERATIONS = 1
random.seed(5438)
np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [26]:
model = DualEmbPredictor(embedding_dim=15, hidden_dim=4, num_epochs=50)

In [27]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]]

In [28]:
model.fit(X, y, validation_set=0.1)

Epoch 1/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 514.52it/s, loss=1.3115]


Validation Loss: 1.7720
Epoch 2/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 517.71it/s, loss=1.1544]


Validation Loss: 1.6667
Epoch 3/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 498.67it/s, loss=1.1357]


Validation Loss: 1.6315
Epoch 4/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 569.83it/s, loss=1.1464]


Validation Loss: 1.6159
Epoch 5/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 522.42it/s, loss=1.1610]


Validation Loss: 1.6066
Epoch 6/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 510.11it/s, loss=1.1616]


Validation Loss: 1.6009
Epoch 7/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 517.58it/s, loss=1.1647]


Validation Loss: 1.5972
Epoch 8/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 565.61it/s, loss=1.1686]


Validation Loss: 1.5949
Epoch 9/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 508.80it/s, loss=1.1627]


Validation Loss: 1.5933
Epoch 10/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 499.65it/s, loss=1.1677]


Validation Loss: 1.5919
Epoch 11/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 540.92it/s, loss=1.1687]


Validation Loss: 1.5910
Epoch 12/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 554.67it/s, loss=1.1657]


Validation Loss: 1.5902
Epoch 13/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 491.83it/s, loss=1.1661]


Validation Loss: 1.5895
Epoch 14/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 472.78it/s, loss=1.1683]


Validation Loss: 1.5891
Epoch 15/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 432.22it/s, loss=1.1673]


Validation Loss: 1.5889
Epoch 16/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 405.95it/s, loss=1.1704]


Validation Loss: 1.5887
Epoch 17/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:11<00:00, 364.08it/s, loss=1.1713]


Validation Loss: 1.5887
Epoch 18/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 427.23it/s, loss=1.1724]


Validation Loss: 1.5881
Epoch 19/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 491.16it/s, loss=1.1756]


Validation Loss: 1.5883
Epoch 20/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 458.10it/s, loss=1.1771]


Validation Loss: 1.5877
Epoch 21/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 448.59it/s, loss=1.1745]


Validation Loss: 1.5871
Epoch 22/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 418.19it/s, loss=1.1730]


Validation Loss: 1.5868
Epoch 23/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 460.80it/s, loss=1.1731]


Validation Loss: 1.5867
Epoch 24/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 393.48it/s, loss=1.1712]


Validation Loss: 1.5865
Epoch 25/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 379.45it/s, loss=1.1709]


Validation Loss: 1.5868
Epoch 26/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 432.88it/s, loss=1.1716]


Validation Loss: 1.5866
Epoch 27/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 510.37it/s, loss=1.1722]


Validation Loss: 1.5868
Epoch 28/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 478.66it/s, loss=1.1744]


Validation Loss: 1.5870
Epoch 29/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 473.75it/s, loss=1.1759]


Validation Loss: 1.5869
Epoch 30/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 440.79it/s, loss=1.1759]


Validation Loss: 1.5870
Epoch 31/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 399.29it/s, loss=1.1768]


Validation Loss: 1.5874
Epoch 32/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 446.91it/s, loss=1.1779]


Validation Loss: 1.5874
Epoch 33/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 507.30it/s, loss=1.1785]


Validation Loss: 1.5879
Epoch 34/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 492.95it/s, loss=1.1790]


Validation Loss: 1.5879
Epoch 35/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 479.96it/s, loss=1.1778]


Validation Loss: 1.5881
Epoch 36/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 426.59it/s, loss=1.1794]


Validation Loss: 1.5885
Epoch 37/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 442.88it/s, loss=1.1802]


Validation Loss: 1.5888
Epoch 38/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 432.99it/s, loss=1.1817]


Validation Loss: 1.5887
Epoch 39/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 445.87it/s, loss=1.1819]


Validation Loss: 1.5889
Epoch 40/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 514.27it/s, loss=1.1844]


Validation Loss: 1.5888
Epoch 41/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 461.83it/s, loss=1.1862]


Validation Loss: 1.5891
Epoch 42/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 458.48it/s, loss=1.1869]


Validation Loss: 1.5891
Epoch 43/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 482.83it/s, loss=1.1888]


Validation Loss: 1.5892
Epoch 44/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 431.15it/s, loss=1.1883]


Validation Loss: 1.5895
Epoch 45/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 460.42it/s, loss=1.1924]


Validation Loss: 1.5896
Epoch 46/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 446.29it/s, loss=1.1884]


Validation Loss: 1.5894
Epoch 47/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 434.40it/s, loss=1.1887]


Validation Loss: 1.5896
Epoch 48/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 392.39it/s, loss=1.1893]


Validation Loss: 1.5896
Epoch 49/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 400.92it/s, loss=1.1898]


Validation Loss: 1.5893
Epoch 50/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 400.38it/s, loss=1.1904]


Validation Loss: 1.5897


In [29]:
model.logit.model.predict(
    model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 0.0}])
)

array([[0.35276479, 0.2944703 , 0.3527649 ]])

In [30]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35276479, 0.2944703 , 0.3527649 ]])

In [31]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35276479, 0.2944703 , 0.3527649 ]])

In [32]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35276479, 0.2944703 , 0.3527649 ]])

In [33]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 1.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.4803569 , 0.27644094, 0.24320216]])

In [38]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 1.0,
            },
        ]
    )
)

array([[0.24320207, 0.27644091, 0.48035702]])

In [40]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": str(random.random()),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35276479, 0.2944703 , 0.3527649 ]])

In [41]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": str(random.random()),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35276479, 0.2944703 , 0.3527649 ]])

In [59]:
model.predict_and_update(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    ),
    pd.DataFrame(
        [
            {
                "team_score": 4,
                "opponent_score": 0,
            },
        ]
    ),
)

array([[0.36784741, 0.29418251, 0.33797008]])

In [74]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35276479, 0.2944703 , 0.3527649 ]])

In [62]:
model.embeddings

{'Argentina': [0.07052040100097656,
  0.0033375637140125036,
  -0.16607806086540222,
  0.033257219940423965,
  0.049469925463199615,
  -0.029851600527763367,
  0.38327550888061523,
  -0.02096114121377468,
  0.07528633624315262,
  -0.021107180044054985,
  0.04682726413011551,
  0.0033649003598839045,
  -0.05041544511914253,
  0.32453086972236633,
  -0.014284412376582623],
 'Brazil': [0.07052040100097656,
  0.0033375637140125036,
  -0.16607806086540222,
  0.033257219940423965,
  0.049469925463199615,
  -0.029851600527763367,
  0.38327550888061523,
  -0.02096114121377468,
  0.07528633624315262,
  -0.021107180044054985,
  0.04682726413011551,
  0.0033649003598839045,
  -0.05041544511914253,
  0.32453086972236633,
  -0.014284412376582623]}

In [78]:
model.predict_and_update(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    ),
    pd.DataFrame(
        [
            {
                "team_score": 0,
                "opponent_score": 10,
            },
        ]
    ),
)

array([[0.36784741, 0.29418251, 0.33797008]])

In [79]:
model.embeddings

{'Argentina': [0.07052040100097656,
  0.0033375637140125036,
  -0.16607806086540222,
  0.033257219940423965,
  0.049469925463199615,
  -0.029851600527763367,
  0.38327550888061523,
  -0.02096114121377468,
  0.07528633624315262,
  -0.021107180044054985,
  0.04682726413011551,
  0.0033649003598839045,
  -0.05041544511914253,
  0.32453086972236633,
  -0.014284412376582623],
 'Brazil': [0.07052040100097656,
  0.0033375637140125036,
  -0.16607806086540222,
  0.033257219940423965,
  0.049469925463199615,
  -0.029851600527763367,
  0.38327550888061523,
  -0.02096114121377468,
  0.07528633624315262,
  -0.021107180044054985,
  0.04682726413011551,
  0.0033649003598839045,
  -0.05041544511914253,
  0.32453086972236633,
  -0.014284412376582623]}