In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.dualemb import DualEmbPredictor

In [2]:
ITERATIONS = 1
random.seed(5438)
np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [11]:
model = DualEmbPredictor(num_epochs=100)

In [12]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]]

In [13]:
model.fit(X, y, validation_set=0.1)

Epoch 1/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 502.37it/s, loss=2.6108]


Validation Loss: 1.8676
Epoch 2/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 475.52it/s, loss=2.0741]


Validation Loss: 1.7517
Epoch 3/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:06<00:00, 588.23it/s, loss=1.9239]


Validation Loss: 1.7078
Epoch 4/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 469.31it/s, loss=1.8964]


Validation Loss: 1.6859
Epoch 5/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 461.39it/s, loss=1.8855]


Validation Loss: 1.6731
Epoch 6/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 452.18it/s, loss=1.8914]


Validation Loss: 1.6650
Epoch 7/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 486.92it/s, loss=1.8887]


Validation Loss: 1.6592
Epoch 8/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 425.49it/s, loss=1.8799]


Validation Loss: 1.6548
Epoch 9/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 491.31it/s, loss=1.8713]


Validation Loss: 1.6514
Epoch 10/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 566.41it/s, loss=1.8704]


Validation Loss: 1.6490
Epoch 11/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 446.20it/s, loss=1.8650]


Validation Loss: 1.6468
Epoch 12/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 448.26it/s, loss=1.8543]


Validation Loss: 1.6451
Epoch 13/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 521.51it/s, loss=1.8533]


Validation Loss: 1.6437
Epoch 14/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 560.70it/s, loss=1.8550]


Validation Loss: 1.6424
Epoch 15/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 445.14it/s, loss=1.8597]


Validation Loss: 1.6419
Epoch 16/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 418.31it/s, loss=1.8545]


Validation Loss: 1.6406
Epoch 17/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 475.49it/s, loss=1.8541]


Validation Loss: 1.6400
Epoch 18/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 396.15it/s, loss=1.8522]


Validation Loss: 1.6395
Epoch 19/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 400.78it/s, loss=1.8503]


Validation Loss: 1.6392
Epoch 20/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 469.86it/s, loss=1.8507]


Validation Loss: 1.6384
Epoch 21/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:06<00:00, 588.09it/s, loss=1.8511]


Validation Loss: 1.6382
Epoch 22/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 444.04it/s, loss=1.8464]


Validation Loss: 1.6377
Epoch 23/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 379.73it/s, loss=1.8401]


Validation Loss: 1.6373
Epoch 24/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 412.87it/s, loss=1.8393]


Validation Loss: 1.6371
Epoch 25/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 388.53it/s, loss=1.8389]


Validation Loss: 1.6370
Epoch 26/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 390.28it/s, loss=1.8379]


Validation Loss: 1.6368
Epoch 27/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 474.86it/s, loss=1.8363]


Validation Loss: 1.6365
Epoch 28/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 400.49it/s, loss=1.8353]


Validation Loss: 1.6363
Epoch 29/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 392.43it/s, loss=1.8321]


Validation Loss: 1.6363
Epoch 30/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 420.53it/s, loss=1.8304]


Validation Loss: 1.6362
Epoch 31/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 465.79it/s, loss=1.8298]


Validation Loss: 1.6362
Epoch 32/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 422.69it/s, loss=1.8298]


Validation Loss: 1.6359
Epoch 33/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 426.86it/s, loss=1.8262]


Validation Loss: 1.6358
Epoch 34/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:06<00:00, 577.20it/s, loss=1.8301]


Validation Loss: 1.6358
Epoch 35/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 465.74it/s, loss=1.8304]


Validation Loss: 1.6356
Epoch 36/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 475.75it/s, loss=1.8302]


Validation Loss: 1.6356
Epoch 37/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 475.49it/s, loss=1.8301]


Validation Loss: 1.6353
Epoch 38/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 487.69it/s, loss=1.8295]


Validation Loss: 1.6349
Epoch 39/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 434.54it/s, loss=1.8290]


Validation Loss: 1.6344
Epoch 40/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 465.93it/s, loss=1.8294]


Validation Loss: 1.6341
Epoch 41/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 490.37it/s, loss=1.8287]


Validation Loss: 1.6339
Epoch 42/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 413.53it/s, loss=1.8293]


Validation Loss: 1.6337
Epoch 43/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 414.89it/s, loss=1.8291]


Validation Loss: 1.6332
Epoch 44/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 388.16it/s, loss=1.8280]


Validation Loss: 1.6331
Epoch 45/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:11<00:00, 348.28it/s, loss=1.8281]


Validation Loss: 1.6329
Epoch 46/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 288.86it/s, loss=1.8292]


Validation Loss: 1.6328
Epoch 47/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 419.08it/s, loss=1.8298]


Validation Loss: 1.6325
Epoch 48/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 399.21it/s, loss=1.8292]


Validation Loss: 1.6321
Epoch 49/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 384.40it/s, loss=1.8339]


Validation Loss: 1.6315
Epoch 50/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 386.52it/s, loss=1.8343]


Validation Loss: 1.6307
Epoch 51/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 385.53it/s, loss=1.8330]


Validation Loss: 1.6298
Epoch 52/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 393.64it/s, loss=1.8413]


Validation Loss: 1.6294
Epoch 53/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 448.64it/s, loss=1.8453]


Validation Loss: 1.6292
Epoch 54/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 422.64it/s, loss=1.8599]


Validation Loss: 1.6287
Epoch 55/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 430.21it/s, loss=1.8734]


Validation Loss: 1.6285
Epoch 56/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 429.47it/s, loss=1.8808]


Validation Loss: 1.6280
Epoch 57/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 422.79it/s, loss=1.8832]


Validation Loss: 1.6279
Epoch 58/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 366.39it/s, loss=1.8863]


Validation Loss: 1.6283
Epoch 59/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 431.84it/s, loss=1.8876]


Validation Loss: 1.6283
Epoch 60/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 550.52it/s, loss=1.8908]


Validation Loss: 1.6282
Epoch 61/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 439.74it/s, loss=1.8903]


Validation Loss: 1.6282
Epoch 62/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 428.81it/s, loss=1.8877]


Validation Loss: 1.6281
Epoch 63/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 519.31it/s, loss=1.8843]


Validation Loss: 1.6281
Epoch 64/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 433.24it/s, loss=1.8835]


Validation Loss: 1.6281
Epoch 65/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 436.12it/s, loss=1.8784]


Validation Loss: 1.6282
Epoch 66/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 401.33it/s, loss=1.8770]


Validation Loss: 1.6282
Epoch 67/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 489.94it/s, loss=1.8769]


Validation Loss: 1.6282
Epoch 68/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 430.91it/s, loss=1.8726]


Validation Loss: 1.6281
Epoch 69/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 429.19it/s, loss=1.8704]


Validation Loss: 1.6280
Epoch 70/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 511.34it/s, loss=1.8688]


Validation Loss: 1.6282
Epoch 71/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 439.93it/s, loss=1.8672]


Validation Loss: 1.6281
Epoch 72/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 403.79it/s, loss=1.8654]


Validation Loss: 1.6283
Epoch 73/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 446.76it/s, loss=1.8612]


Validation Loss: 1.6285
Epoch 74/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 566.19it/s, loss=1.8624]


Validation Loss: 1.6284
Epoch 75/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 469.94it/s, loss=1.8600]


Validation Loss: 1.6282
Epoch 76/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 455.07it/s, loss=1.8554]


Validation Loss: 1.6282
Epoch 77/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 533.45it/s, loss=1.8567]


Validation Loss: 1.6280
Epoch 78/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 446.38it/s, loss=1.8533]


Validation Loss: 1.6281
Epoch 79/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 290.29it/s, loss=1.8531]


Validation Loss: 1.6280
Epoch 80/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 441.59it/s, loss=1.8513]


Validation Loss: 1.6280
Epoch 81/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 427.15it/s, loss=1.8528]


Validation Loss: 1.6278
Epoch 82/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 384.91it/s, loss=1.8526]


Validation Loss: 1.6277
Epoch 83/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 368.61it/s, loss=1.8511]


Validation Loss: 1.6276
Epoch 84/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:11<00:00, 356.38it/s, loss=1.8500]


Validation Loss: 1.6277
Epoch 85/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:11<00:00, 351.69it/s, loss=1.8486]


Validation Loss: 1.6275
Epoch 86/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 389.21it/s, loss=1.8475]


Validation Loss: 1.6277
Epoch 87/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 412.28it/s, loss=1.8473]


Validation Loss: 1.6276
Epoch 88/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 414.26it/s, loss=1.8468]


Validation Loss: 1.6276
Epoch 89/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 440.16it/s, loss=1.8452]


Validation Loss: 1.6274
Epoch 90/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 535.09it/s, loss=1.8483]


Validation Loss: 1.6274
Epoch 91/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 431.11it/s, loss=1.8459]


Validation Loss: 1.6275
Epoch 92/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 415.29it/s, loss=1.8442]


Validation Loss: 1.6274
Epoch 93/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:07<00:00, 558.38it/s, loss=1.8436]


Validation Loss: 1.6274
Epoch 94/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 451.76it/s, loss=1.8425]


Validation Loss: 1.6275
Epoch 95/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 388.79it/s, loss=1.8360]


Validation Loss: 1.6275
Epoch 96/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 422.80it/s, loss=1.8342]


Validation Loss: 1.6276
Epoch 97/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:09<00:00, 407.67it/s, loss=1.8284]


Validation Loss: 1.6277
Epoch 98/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:11<00:00, 362.94it/s, loss=1.8296]


Validation Loss: 1.6278
Epoch 99/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 386.58it/s, loss=1.8241]


Validation Loss: 1.6276
Epoch 100/100


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:08<00:00, 495.97it/s, loss=1.8250]


Validation Loss: 1.6278


In [ ]:
model.logit.model.predict(
    model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 0.0}])
)

In [38]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

NameError: name 'elo' is not defined

In [12]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.40166393, 0.28372598, 0.31461009]])

In [13]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35695543, 0.28608557, 0.356959  ]])

In [14]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 1.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.42654169, 0.28053235, 0.29292596]])

In [15]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 1.0,
            },
        ]
    )
)

array([[0.29292273, 0.28053177, 0.4265455 ]])

In [16]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.92678624, 0.04944971, 0.02376405]])

In [17]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.92678624, 0.04944971, 0.02376405]])