In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.dualemb import DualEmbPredictor

In [2]:
ITERATIONS = 1
random.seed(5438)
np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [5]:
model = DualEmbPredictor(num_epochs=100)

In [6]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]]

In [7]:
model.fit(X, y, validation_set=0.1)

Epoch 1/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:30<00:00, 130.56it/s, loss=1.4250]


Validation Loss: 1.8095
Epoch 2/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 168.89it/s, loss=1.3643]


Validation Loss: 1.6948
Epoch 3/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 174.06it/s, loss=1.3870]


Validation Loss: 1.6500
Epoch 4/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 140.49it/s, loss=1.3975]


Validation Loss: 1.6287
Epoch 5/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 148.94it/s, loss=1.4017]


Validation Loss: 1.6151
Epoch 6/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 146.70it/s, loss=1.4141]


Validation Loss: 1.6059
Epoch 7/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 166.56it/s, loss=1.4249]


Validation Loss: 1.5994
Epoch 8/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 164.25it/s, loss=1.4316]


Validation Loss: 1.5946
Epoch 9/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 164.38it/s, loss=1.4369]


Validation Loss: 1.5897
Epoch 10/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 154.33it/s, loss=1.4313]


Validation Loss: 1.5852
Epoch 11/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 167.37it/s, loss=1.4217]


Validation Loss: 1.5819
Epoch 12/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 152.16it/s, loss=1.4248]


Validation Loss: 1.5796
Epoch 13/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 174.58it/s, loss=1.4267]


Validation Loss: 1.5776
Epoch 14/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 175.39it/s, loss=1.4267]


Validation Loss: 1.5756
Epoch 15/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 169.07it/s, loss=1.4273]


Validation Loss: 1.5739
Epoch 16/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 151.78it/s, loss=1.4249]


Validation Loss: 1.5726
Epoch 17/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 186.61it/s, loss=1.4221]


Validation Loss: 1.5715
Epoch 18/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 188.37it/s, loss=1.4224]


Validation Loss: 1.5705
Epoch 19/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 191.76it/s, loss=1.4217]


Validation Loss: 1.5696
Epoch 20/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 175.80it/s, loss=1.4212]


Validation Loss: 1.5688
Epoch 21/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 205.62it/s, loss=1.4207]


Validation Loss: 1.5681
Epoch 22/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 172.40it/s, loss=1.4177]


Validation Loss: 1.5673
Epoch 23/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 164.96it/s, loss=1.4167]


Validation Loss: 1.5665
Epoch 24/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 165.31it/s, loss=1.4162]


Validation Loss: 1.5660
Epoch 25/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 198.40it/s, loss=1.4160]


Validation Loss: 1.5654
Epoch 26/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 201.48it/s, loss=1.4144]


Validation Loss: 1.5648
Epoch 27/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 181.43it/s, loss=1.4119]


Validation Loss: 1.5642
Epoch 28/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 163.40it/s, loss=1.4119]


Validation Loss: 1.5637
Epoch 29/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 139.66it/s, loss=1.4114]


Validation Loss: 1.5632
Epoch 30/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 152.11it/s, loss=1.4107]


Validation Loss: 1.5628
Epoch 31/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 151.82it/s, loss=1.4123]


Validation Loss: 1.5624
Epoch 32/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 152.22it/s, loss=1.4136]


Validation Loss: 1.5619
Epoch 33/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 146.26it/s, loss=1.4124]


Validation Loss: 1.5615
Epoch 34/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 154.54it/s, loss=1.4113]


Validation Loss: 1.5610
Epoch 35/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 152.77it/s, loss=1.4101]


Validation Loss: 1.5606
Epoch 36/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 162.80it/s, loss=1.4108]


Validation Loss: 1.5601
Epoch 37/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:30<00:00, 134.06it/s, loss=1.4106]


Validation Loss: 1.5599
Epoch 38/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 148.08it/s, loss=1.4107]


Validation Loss: 1.5595
Epoch 39/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:25<00:00, 156.81it/s, loss=1.4108]


Validation Loss: 1.5591
Epoch 40/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 142.48it/s, loss=1.4094]


Validation Loss: 1.5587
Epoch 41/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:29<00:00, 138.30it/s, loss=1.4093]


Validation Loss: 1.5584
Epoch 42/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 147.04it/s, loss=1.4104]


Validation Loss: 1.5581
Epoch 43/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 166.92it/s, loss=1.4106]


Validation Loss: 1.5576
Epoch 44/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 188.48it/s, loss=1.4105]


Validation Loss: 1.5573
Epoch 45/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 187.89it/s, loss=1.4108]


Validation Loss: 1.5570
Epoch 46/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 151.63it/s, loss=1.4118]


Validation Loss: 1.5567
Epoch 47/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 146.54it/s, loss=1.4101]


Validation Loss: 1.5564
Epoch 48/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 152.00it/s, loss=1.4108]


Validation Loss: 1.5561
Epoch 49/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 141.65it/s, loss=1.4100]


Validation Loss: 1.5560
Epoch 50/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 153.35it/s, loss=1.4087]


Validation Loss: 1.5558
Epoch 51/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 146.63it/s, loss=1.4090]


Validation Loss: 1.5554
Epoch 52/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 171.62it/s, loss=1.4069]


Validation Loss: 1.5552
Epoch 53/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 188.31it/s, loss=1.4056]


Validation Loss: 1.5548
Epoch 54/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 181.16it/s, loss=1.4057]


Validation Loss: 1.5547
Epoch 55/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 151.81it/s, loss=1.4073]


Validation Loss: 1.5544
Epoch 56/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 144.17it/s, loss=1.4072]


Validation Loss: 1.5542
Epoch 57/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:29<00:00, 136.29it/s, loss=1.4069]


Validation Loss: 1.5541
Epoch 58/100


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:42<00:00, 95.33it/s, loss=1.4059]


Validation Loss: 1.5540
Epoch 59/100


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:45<00:00, 88.64it/s, loss=1.4065]


Validation Loss: 1.5538
Epoch 60/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:32<00:00, 123.52it/s, loss=1.4056]


Validation Loss: 1.5537
Epoch 61/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 165.23it/s, loss=1.4068]


Validation Loss: 1.5535
Epoch 62/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 198.01it/s, loss=1.4063]


Validation Loss: 1.5534
Epoch 63/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 161.20it/s, loss=1.4064]


Validation Loss: 1.5532
Epoch 64/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 169.68it/s, loss=1.4057]


Validation Loss: 1.5532
Epoch 65/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 172.37it/s, loss=1.4056]


Validation Loss: 1.5530
Epoch 66/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:30<00:00, 129.79it/s, loss=1.4065]


Validation Loss: 1.5529
Epoch 67/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 148.48it/s, loss=1.4051]


Validation Loss: 1.5528
Epoch 68/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 150.45it/s, loss=1.4043]


Validation Loss: 1.5527
Epoch 69/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:25<00:00, 154.75it/s, loss=1.4032]


Validation Loss: 1.5526
Epoch 70/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 144.73it/s, loss=1.4022]


Validation Loss: 1.5525
Epoch 71/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 140.06it/s, loss=1.4030]


Validation Loss: 1.5524
Epoch 72/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 142.86it/s, loss=1.4026]


Validation Loss: 1.5523
Epoch 73/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 146.11it/s, loss=1.4033]


Validation Loss: 1.5522
Epoch 74/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 178.19it/s, loss=1.4033]


Validation Loss: 1.5521
Epoch 75/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 177.46it/s, loss=1.4012]


Validation Loss: 1.5520
Epoch 76/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 150.79it/s, loss=1.4017]


Validation Loss: 1.5519
Epoch 77/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 141.58it/s, loss=1.4005]


Validation Loss: 1.5519
Epoch 78/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:29<00:00, 134.88it/s, loss=1.3999]


Validation Loss: 1.5517
Epoch 79/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 194.68it/s, loss=1.3984]


Validation Loss: 1.5517
Epoch 80/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 169.85it/s, loss=1.3999]


Validation Loss: 1.5516
Epoch 81/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 186.28it/s, loss=1.4014]


Validation Loss: 1.5514
Epoch 82/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:25<00:00, 158.35it/s, loss=1.3990]


Validation Loss: 1.5513
Epoch 83/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 194.24it/s, loss=1.3981]


Validation Loss: 1.5512
Epoch 84/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 186.67it/s, loss=1.3964]


Validation Loss: 1.5512
Epoch 85/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:25<00:00, 155.55it/s, loss=1.3975]


Validation Loss: 1.5510
Epoch 86/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 145.55it/s, loss=1.3971]


Validation Loss: 1.5509
Epoch 87/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:25<00:00, 158.02it/s, loss=1.3965]


Validation Loss: 1.5509
Epoch 88/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:29<00:00, 137.54it/s, loss=1.3965]


Validation Loss: 1.5508
Epoch 89/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:34<00:00, 115.15it/s, loss=1.3959]


Validation Loss: 1.5508
Epoch 90/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:29<00:00, 137.09it/s, loss=1.3965]


Validation Loss: 1.5507
Epoch 91/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 141.60it/s, loss=1.3962]


Validation Loss: 1.5508
Epoch 92/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 145.17it/s, loss=1.3972]


Validation Loss: 1.5507
Epoch 93/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:26<00:00, 153.14it/s, loss=1.3976]


Validation Loss: 1.5506
Epoch 94/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:29<00:00, 134.44it/s, loss=1.3962]


Validation Loss: 1.5506
Epoch 95/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 141.17it/s, loss=1.3957]


Validation Loss: 1.5506
Epoch 96/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:29<00:00, 136.06it/s, loss=1.3952]


Validation Loss: 1.5505
Epoch 97/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:28<00:00, 141.76it/s, loss=1.3971]


Validation Loss: 1.5505
Epoch 98/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 147.17it/s, loss=1.3971]


Validation Loss: 1.5505
Epoch 99/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 161.64it/s, loss=1.3965]


Validation Loss: 1.5504
Epoch 100/100


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 194.94it/s, loss=1.3977]


Validation Loss: 1.5503


In [16]:
model.logit.model.predict(model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 5.0}]))

array([[0.99010998, 0.00691566, 0.00297436]])

In [38]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

NameError: name 'elo' is not defined

In [12]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.40166393, 0.28372598, 0.31461009]])

In [13]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35695543, 0.28608557, 0.356959  ]])

In [14]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 1.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.42654169, 0.28053235, 0.29292596]])

In [15]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 1.0,
            },
        ]
    )
)

array([[0.29292273, 0.28053177, 0.4265455 ]])

In [16]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.92678624, 0.04944971, 0.02376405]])

In [17]:
elo.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.92678624, 0.04944971, 0.02376405]])