In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.dualemb import DualEmbPredictor

In [2]:
ITERATIONS = 1
random.seed(5438)
np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [14]:
model = DualEmbPredictor(embedding_dim=20, train_learning_rate=0.001, num_epochs=50)

In [15]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]] / 10.0

In [16]:
model.fit(X, y, validation_set=0.1)

Epoch 1/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:14<00:00, 270.46it/s, loss=0.0184]


Validation Loss: 0.0185
Epoch 2/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:15<00:00, 268.04it/s, loss=0.0158]


Validation Loss: 0.0172
Epoch 3/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:10<00:00, 381.97it/s, loss=0.0155]


Validation Loss: 0.0166
Epoch 4/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 307.19it/s, loss=0.0158]


Validation Loss: 0.0164
Epoch 5/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 332.51it/s, loss=0.0157]


Validation Loss: 0.0163
Epoch 6/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 324.51it/s, loss=0.0157]


Validation Loss: 0.0162
Epoch 7/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 317.14it/s, loss=0.0158]


Validation Loss: 0.0162
Epoch 8/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 325.07it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 9/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 294.84it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 10/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 298.07it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 11/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:12<00:00, 324.97it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 12/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:13<00:00, 304.45it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 13/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:15<00:00, 258.88it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 14/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:14<00:00, 268.40it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 15/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:15<00:00, 258.40it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 16/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:14<00:00, 268.89it/s, loss=0.0158]


Validation Loss: 0.0161
Epoch 17/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 195.99it/s, loss=0.0157]


Validation Loss: 0.0161
Epoch 18/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 173.11it/s, loss=0.0156]


Validation Loss: 0.0161
Epoch 19/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 169.11it/s, loss=0.0155]


Validation Loss: 0.0161
Epoch 20/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 209.72it/s, loss=0.0155]


Validation Loss: 0.0161
Epoch 21/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 187.30it/s, loss=0.0153]


Validation Loss: 0.0161
Epoch 22/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 199.59it/s, loss=0.0152]


Validation Loss: 0.0161
Epoch 23/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 168.55it/s, loss=0.0151]


Validation Loss: 0.0161
Epoch 24/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 166.99it/s, loss=0.0150]


Validation Loss: 0.0161
Epoch 25/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:34<00:00, 117.61it/s, loss=0.0149]


Validation Loss: 0.0161
Epoch 26/50


100%|██████████████████████████████████████████████████████████████████| 4022/4022 [00:49<00:00, 81.64it/s, loss=0.0147]


Validation Loss: 0.0161
Epoch 27/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:38<00:00, 103.62it/s, loss=0.0146]


Validation Loss: 0.0161
Epoch 28/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:35<00:00, 112.21it/s, loss=0.0145]


Validation Loss: 0.0161
Epoch 29/50


100%|██████████████████████████████████████████████████████████████████| 4022/4022 [00:41<00:00, 98.04it/s, loss=0.0144]


Validation Loss: 0.0161
Epoch 30/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:31<00:00, 129.55it/s, loss=0.0143]


Validation Loss: 0.0161
Epoch 31/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:18<00:00, 220.42it/s, loss=0.0142]


Validation Loss: 0.0161
Epoch 32/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 187.74it/s, loss=0.0141]


Validation Loss: 0.0162
Epoch 33/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 183.36it/s, loss=0.0140]


Validation Loss: 0.0162
Epoch 34/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 168.78it/s, loss=0.0139]


Validation Loss: 0.0162
Epoch 35/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 173.83it/s, loss=0.0138]


Validation Loss: 0.0162
Epoch 36/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:23<00:00, 174.03it/s, loss=0.0137]


Validation Loss: 0.0162
Epoch 37/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:24<00:00, 167.50it/s, loss=0.0136]


Validation Loss: 0.0162
Epoch 38/50


100%|██████████████████████████████████████████████████████████████████| 4022/4022 [00:41<00:00, 96.69it/s, loss=0.0135]


Validation Loss: 0.0162
Epoch 39/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:27<00:00, 144.69it/s, loss=0.0135]


Validation Loss: 0.0162
Epoch 40/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 199.43it/s, loss=0.0134]


Validation Loss: 0.0162
Epoch 41/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 206.98it/s, loss=0.0133]


Validation Loss: 0.0163
Epoch 42/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 184.78it/s, loss=0.0133]


Validation Loss: 0.0163
Epoch 43/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 182.48it/s, loss=0.0132]


Validation Loss: 0.0163
Epoch 44/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 178.15it/s, loss=0.0131]


Validation Loss: 0.0163
Epoch 45/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:21<00:00, 190.36it/s, loss=0.0130]


Validation Loss: 0.0163
Epoch 46/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:20<00:00, 194.44it/s, loss=0.0129]


Validation Loss: 0.0163
Epoch 47/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:22<00:00, 179.08it/s, loss=0.0129]


Validation Loss: 0.0163
Epoch 48/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 209.38it/s, loss=0.0128]


Validation Loss: 0.0163
Epoch 49/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 209.26it/s, loss=0.0127]


Validation Loss: 0.0163
Epoch 50/50


100%|█████████████████████████████████████████████████████████████████| 4022/4022 [00:19<00:00, 205.88it/s, loss=0.0126]


Validation Loss: 0.0164


In [17]:
model.logit.model.predict(
    model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 0.0}])
)

array([[0.3563767 , 0.28724496, 0.35637834]])

In [18]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.3563767 , 0.28724496, 0.35637834]])

In [19]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.3563767 , 0.28724496, 0.35637834]])

In [20]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.3563767 , 0.28724496, 0.35637834]])

In [21]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 1.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.46320376, 0.27464009, 0.26215614]])

In [22]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": random.random(),
                "opponent_id": random.random(),
                "team_at_home": 0.0,
                "opponent_at_home": 1.0,
            },
        ]
    )
)

array([[0.26215476, 0.2746397 , 0.46320554]])

In [23]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": str(random.random()),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.3563767 , 0.28724496, 0.35637834]])

In [24]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": str(random.random()),
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.3563767 , 0.28724496, 0.35637834]])

In [25]:
model.predict_and_update(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    ),
    pd.DataFrame(
        [
            {
                "team_score": 4,
                "opponent_score": 0,
            },
        ]
    ),
)

array([[0.3563767 , 0.28724496, 0.35637834]])

In [26]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.3768359 , 0.28673391, 0.33643019]])

In [27]:
model.embeddings

{'Argentina': [0.10502047836780548,
  -0.20771971344947815,
  0.11982806026935577,
  0.09470178186893463,
  0.15561939775943756,
  0.23406867682933807,
  -0.07347624003887177,
  -0.018483713269233704,
  0.15188179910182953,
  0.11879277974367142,
  0.15726275742053986,
  -0.1242038831114769,
  -0.17651957273483276,
  0.15905651450157166,
  0.06183586269617081,
  0.023565897718071938,
  -0.036223795264959335,
  -0.01191636547446251,
  -0.0759628638625145,
  0.04775892198085785],
 'Brazil': [0.10502047836780548,
  -0.20771972835063934,
  0.09982806444168091,
  0.07470178604125977,
  0.15561939775943756,
  0.2140686810016632,
  -0.07347624003887177,
  -0.018483690917491913,
  0.13188178837299347,
  0.11879278719425201,
  0.17726273834705353,
  -0.10420388728380203,
  -0.1565195769071579,
  0.13905653357505798,
  0.04183587059378624,
  0.023565903306007385,
  -0.0562237873673439,
  0.008083634078502655,
  -0.05596286803483963,
  0.027758922427892685]}

In [50]:
model.predict_and_update(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    ),
    pd.DataFrame(
        [
            {
                "team_score": 10,
                "opponent_score": 0,
            },
        ]
    ),
)

array([[0.41903177, 0.28268662, 0.29828161]])

In [42]:
model.embeddings

{'Argentina': [0.1450204849243164,
  -0.1677197515964508,
  0.09982806444168091,
  0.07470178604125977,
  0.11561938375234604,
  0.2140686810016632,
  -0.033476248383522034,
  -0.058483682572841644,
  0.13188178837299347,
  0.07879278808832169,
  0.1772627830505371,
  -0.10420388728380203,
  -0.1565195620059967,
  0.1390565037727356,
  0.04183586686849594,
  -0.016434090211987495,
  -0.0562237873673439,
  0.008083632215857506,
  -0.05596286803483963,
  0.027758926153182983],
 'Brazil': [0.1450204849243164,
  -0.16771972179412842,
  0.11982806771993637,
  0.09470178186893463,
  0.11561939865350723,
  0.23406869173049927,
  -0.033476248383522034,
  -0.05848367512226105,
  0.15188178420066833,
  0.07879279553890228,
  0.15726274251937866,
  -0.1242038831114769,
  -0.17651958763599396,
  0.15905654430389404,
  0.061835870146751404,
  -0.016434088349342346,
  -0.03622378781437874,
  -0.011916364543139935,
  -0.0759628638625145,
  0.04775891825556755]}

In [45]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.33642859, 0.28673383, 0.37683758]])