In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.eloe import ELOePredictor

In [2]:
ITERATIONS = 1
# random.seed(5438)
# np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [5]:
model = ELOePredictor()

In [6]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]]

In [7]:
model.fit(X, y)

Epoch 1/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 498.09it/s, loss=1.2489]


Epoch 2/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 508.94it/s, loss=1.2424]


Epoch 3/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 506.79it/s, loss=1.2098]


Epoch 4/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 504.82it/s, loss=1.1305]


Epoch 5/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 527.11it/s, loss=1.1297]


Epoch 6/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 544.78it/s, loss=1.1313]


Epoch 7/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 544.90it/s, loss=1.1342]


Epoch 8/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:01<00:00, 572.73it/s, loss=1.1436]


Epoch 9/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 558.69it/s, loss=1.1505]


Epoch 10/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 515.42it/s, loss=1.1465]


Epoch 11/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 546.99it/s, loss=1.1520]


Epoch 12/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 503.80it/s, loss=1.1473]


Epoch 13/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 502.90it/s, loss=1.1420]


Epoch 14/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 478.19it/s, loss=1.1358]


Epoch 15/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 510.31it/s, loss=1.1305]


Epoch 16/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 548.28it/s, loss=1.1245]


Epoch 17/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 508.36it/s, loss=1.1195]


Epoch 18/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 483.81it/s, loss=1.1157]


Epoch 19/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 487.03it/s, loss=1.1130]


Epoch 20/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 487.74it/s, loss=1.1103]


Epoch 21/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 467.03it/s, loss=1.1081]


Epoch 22/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 495.11it/s, loss=1.1064]


Epoch 23/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 485.08it/s, loss=1.1049]


Epoch 24/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 482.66it/s, loss=1.1035]


Epoch 25/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 420.25it/s, loss=1.1025]


Epoch 26/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 461.72it/s, loss=1.1019]


Epoch 27/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 407.83it/s, loss=1.1013]


Epoch 28/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 466.30it/s, loss=1.1009]


Epoch 29/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 430.18it/s, loss=1.1005]


Epoch 30/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 425.06it/s, loss=1.1002]


Epoch 31/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 452.90it/s, loss=1.0998]


Epoch 32/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 481.64it/s, loss=1.0997]


Epoch 33/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 545.14it/s, loss=1.0996]


Epoch 34/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 466.46it/s, loss=1.0995]


Epoch 35/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 420.56it/s, loss=1.0997]


Epoch 36/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 438.50it/s, loss=1.0998]


Epoch 37/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 489.44it/s, loss=1.0998]


Epoch 38/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 451.32it/s, loss=1.0998]


Epoch 39/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 516.11it/s, loss=1.0996]


Epoch 40/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 465.20it/s, loss=1.0994]


Epoch 41/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 504.29it/s, loss=1.0991]


Epoch 42/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 481.84it/s, loss=1.0988]


Epoch 43/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 399.43it/s, loss=1.0985]


Epoch 44/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 425.00it/s, loss=1.0982]


Epoch 45/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 463.76it/s, loss=1.0977]


Epoch 46/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 499.83it/s, loss=1.0973]


Epoch 47/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 448.37it/s, loss=1.0969]


Epoch 48/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 441.52it/s, loss=1.0964]


Epoch 49/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 448.31it/s, loss=1.0958]


Epoch 50/50


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1118/1118 [00:02<00:00, 464.52it/s, loss=1.0955]


In [8]:
model.logit.model.predict(
    model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 0.0}])
)

array([[0.3525777 , 0.29484448, 0.35257783]])

In [9]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.3525777 , 0.29484448, 0.35257783]])

In [10]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.3525777 , 0.29484448, 0.35257783]])

In [11]:
model.predict_and_update(X, y)

/mnt/c/Personal/football-matches-prediction/src/models/eloe.py:317: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pair_X["team_id"] = [0, 1]
/mnt/c/Personal/football-matches-prediction/src/models/eloe.py:318: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pair_X["opponent_id"] = [1, 0]


array([[0.44670959, 0.28464   , 0.2686504 ],
       [0.46417123, 0.28078568, 0.25504309],
       [0.39691415, 0.29244296, 0.31064289],
       ...,
       [0.76852698, 0.14947221, 0.08200081],
       [0.46777844, 0.27992286, 0.25229869],
       [0.808426  , 0.12590906, 0.06566494]], shape=(143005, 3))

In [12]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.44620483, 0.28474328, 0.26905189]])

In [13]:
teams_df = dataset[dataset["fold"].isin(["international"])]
teams = set(teams_df["team_id"].unique().tolist()).union(set(teams_df["opponent_id"].unique().tolist()))
ranking = {team: 0 for team in teams}

for team in ranking:
    for opponent in ranking:
        if team == opponent:
            continue
        pred = model.predict(
            pd.DataFrame(
                [
                    {
                        "team_id": team,
                        "opponent_id": opponent,
                        "team_at_home": 1.0,
                        "opponent_at_home": 0.0,
                    },
                ]
            )
        )
        ranking[team] += float(3 * pred[0][0] + 1 * pred[0][1])

In [14]:
pd.DataFrame(list(ranking.items()), columns=['Team', 'Score']).sort_values(by='Score', ascending=False).reset_index(drop=True).head(20)

Team       Score
0     Argentina  946.327743
1         Spain  930.135258
2        Brazil  929.357910
3      Colombia  920.302178
4      Portugal  916.478607
5        France  912.565350
6       Belgium  901.988310
7       Uruguay  895.639978
8   Netherlands  894.825581
9         Japan  889.398975
10      England  886.496784
11      Germany  885.729335
12        Italy  878.287836
13      Ecuador  869.168562
14      Croatia  854.474716
15      Denmark  848.617626
16      Austria  847.143809
17       Mexico  846.752793
18       Canada  839.802191
19    Australia  838.134218

In [15]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "France",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.52116721, 0.26469713, 0.21413566]])

In [16]:
teams_df = dataset[~dataset["fold"].isin(["international"])]
teams = set(teams_df["team_id"].unique().tolist()).union(set(teams_df["opponent_id"].unique().tolist()))
ranking = {team: 0 for team in teams}

for team in ranking:
    for opponent in ranking:
        if team == opponent:
            continue
        pred = model.predict(
            pd.DataFrame(
                [
                    {
                        "team_id": team,
                        "opponent_id": opponent,
                        "team_at_home": 1.0,
                        "opponent_at_home": 0.0,
                    },
                ]
            )
        )
        ranking[team] += float(3 * pred[0][0] + 1 * pred[0][1])

In [17]:
pd.DataFrame(list(ranking.items()), columns=['Team', 'Score']).sort_values(by='Score', ascending=False).reset_index(drop=True).head(50)

Team        Score
0                             Liverpool Football Club  3172.245637
1                                   FC Bayern München  3169.891280
2                          Real Madrid Club de Fútbol  3163.211136
3          Football Club Internazionale Milano S.p.A.  3144.060349
4   Eindhovense Voetbalvereniging Philips Sport Ve...  3142.571436
5                          Sporting Clube de Portugal  3119.680206
6                               Arsenal Football Club  3101.821369
7                         Bayer 04 Leverkusen Fußball  3093.705195
8                   Atalanta Bergamasca Calcio S.p.a.  3055.503638
9                             Galatasaray Spor Kulübü  3047.040815
10                           The Celtic Football Club  3042.874193
11                  Paris Saint-Germain Football Club  3038.708343
12                                Feyenoord Rotterdam  3021.400951
13                             Futebol Clube do Porto  3015.122272
14                              Futbol Club Barcelona  3012.490378
15                      Manchester City Football Club  3005.983774
16                             Sport Lisboa e Benfica  2997.499341
17                     Newcastle United Football Club  2989.952509
18                                          Palmeiras  2969.366010
19                                   Atlético Mineiro  2966.960345
20                                           Flamengo  2939.757243
21                                  Borussia Dortmund  2936.940406
22                             Fenerbahçe Spor Kulübü  2906.289054
23                     Club Atlético de Madrid S.A.D.  2897.714611
24            Olympiakos Syndesmos Filathlon Peiraios  2896.783136
25                              Chelsea Football Club  2880.288712
26                         Futbolniy Klub Dynamo Kyiv  2859.484908
27                          Associazione Calcio Milan  2859.203336
28                             Juventus Football Club  2843.878216
29                        AO FK Zenit Sankt-Peterburg  2837.167543
30  Panthessalonikios Athlitikos Omilos Konstantin...  2824.999886
31                                      Internacional  2823.000673
32                 Athlitiki Enosi Konstantinoupoleos  2817.696627
33                                         Fluminense  2812.379266
34                      Società Sportiva Lazio S.p.A.  2812.226939
35                     Società Sportiva Calcio Napoli  2808.198766
36                                          Fortaleza  2805.668111
37                                          São Paulo  2803.782847
38                                           Botafogo  2797.420387
39                                        River Plate  2795.982742
40                                             Grêmio  2794.586548
41                                    Vélez Sarsfield  2785.953359
42                             RasenBallsport Leipzig  2773.396392
43                                 AFC Ajax Amsterdam  2772.997432
44                                      RB Bragantino  2767.609346
45                                FC Shakhtar Donetsk  2760.764174
46                               Athletic Club Bilbao  2759.195075
47                      Lille Olympique Sporting Club  2757.972260
48                                  FK Spartak Moskva  2748.711077
49                                       Boca Juniors  2748.467290