In [1]:
import random

import numpy as np
import pandas as pd

from src.dataset import get_dataset
from src.models.elog import ELOgPredictor

In [2]:
ITERATIONS = 1
random.seed(5438)
np.random.seed(5438)

In [3]:
dataset = get_dataset()

/mnt/c/Personal/football-matches-prediction/src/dataset.py:47: DtypeWarning: Columns (11,14,50,102,123,125,129,131,133,135,137,139,141,143,145,147,149,157,158,160,161,163,165,167,169,171,173,184,186,187,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  mls_df = pd.read_csv("data/mls_matches.csv")


In [4]:
dataset

team_id  \
0                                                Scotland   
1                                                 England   
2                                                Scotland   
3                                                 England   
4                                                Scotland   
...                                                   ...   
143000                             Sport Lisboa e Benfica   
143001                    Panathinaikos Athlitikos Omilos   
143002                               Fulham Football Club   
143003  Panthessalonikios Athlitikos Omilos Konstantin...   
143004                         Real Madrid Club de Fútbol   

                                opponent_id  team_at_home  opponent_at_home  \
0                                   England           1.0               0.0   
1                                  Scotland           1.0               0.0   
2                                   England           1.0               0.0   
3                                  Scotland           1.0               0.0   
4                                   England           1.0               0.0   
...                                     ...           ...               ...   
143000              Sporting Clube de Braga           1.0               0.0   
143001                APS Atromitos Athinon           1.0               0.0   
143002                           Watford FC           1.0               0.0   
143003   Athlitiki Enosi Konstantinoupoleos           1.0               0.0   
143004  Real Club Deportivo Mallorca S.A.D.           1.0               0.0   

        team_score  opponent_score           fold  
0                0               0  international  
1                4               2  international  
2                2               1  international  
3                2               2  international  
4                3               0  international  
...            ...             ...            ...  
143000           3               0         europe  
143001           2               1         europe  
143002           4               1         europe  
143003           1               1         europe  
143004           3               0         europe  

[143005 rows x 7 columns]

In [5]:
model = ELOgPredictor()

In [6]:
X = dataset[["team_id", "opponent_id", "team_at_home", "opponent_at_home"]]
y = dataset[["team_score", "opponent_score"]]

In [7]:
model.fit(X, y)

In [18]:
model.logit.model.predict(
    model.logit.params, exog=pd.DataFrame(data=[{"predicted_score_difference": 0.0}])
)

array([[0.35695543, 0.28608557, 0.356959  ]])

In [19]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35695543, 0.28608557, 0.356959  ]])

In [20]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Brazil",
                "opponent_id": "Argentina",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.35695543, 0.28608557, 0.356959  ]])

In [21]:
model.predict_and_update(X, y)

array([[0.42654169, 0.28053235, 0.29292596],
       [0.42858287, 0.28021552, 0.29120161],
       [0.39534216, 0.28433303, 0.3203248 ],
       ...,
       [0.7766678 , 0.14193725, 0.08139495],
       [0.40271483, 0.28361681, 0.31366837],
       [0.83724712, 0.10623802, 0.05651486]], shape=(143005, 3))

In [23]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "Brazil",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.40166393, 0.28372598, 0.31461009]])

In [13]:
teams_df = dataset[dataset["fold"].isin(["international"])]
teams = set(teams_df["team_id"].unique().tolist()).union(set(teams_df["opponent_id"].unique().tolist()))
ranking = {team: 0 for team in teams}

for team in ranking:
    for opponent in ranking:
        if team == opponent:
            continue
        pred = model.predict(
            pd.DataFrame(
                [
                    {
                        "team_id": team,
                        "opponent_id": opponent,
                        "team_at_home": 1.0,
                        "opponent_at_home": 0.0,
                    },
                ]
            )
        )
        ranking[team] += float(3 * pred[0][0] + 1 * pred[0][1])

In [14]:
pd.DataFrame(list(ranking.items()), columns=['Team', 'Score']).sort_values(by='Score', ascending=False).reset_index(drop=True).head(20)

Team       Score
0     Argentina  943.873707
1         Spain  942.472546
2        Brazil  933.425644
3        France  920.838017
4      Colombia  917.252774
5       England  901.298180
6      Portugal  900.326214
7   Netherlands  893.994155
8       Germany  893.672171
9       Belgium  892.570673
10        Italy  887.954825
11      Uruguay  886.311850
12        Japan  877.658962
13      Croatia  869.284786
14      Denmark  854.910328
15         Iran  850.202916
16  South Korea  842.435352
17      Ecuador  837.142692
18      Austria  834.654328
19       Mexico  833.408782

In [15]:
model.predict(
    pd.DataFrame(
        [
            {
                "team_id": "Argentina",
                "opponent_id": "France",
                "team_at_home": 0.0,
                "opponent_at_home": 0.0,
            },
        ]
    )
)

array([[0.45073684, 0.27627149, 0.27299167]])

In [24]:
teams_df = dataset[~dataset["fold"].isin(["international"])]
teams = set(teams_df["team_id"].unique().tolist()).union(set(teams_df["opponent_id"].unique().tolist()))
ranking = {team: 0 for team in teams}

for team in ranking:
    for opponent in ranking:
        if team == opponent:
            continue
        pred = model.predict(
            pd.DataFrame(
                [
                    {
                        "team_id": team,
                        "opponent_id": opponent,
                        "team_at_home": 1.0,
                        "opponent_at_home": 0.0,
                    },
                ]
            )
        )
        ranking[team] += float(3 * pred[0][0] + 1 * pred[0][1])

In [25]:
pd.DataFrame(list(ranking.items()), columns=['Team', 'Score']).sort_values(by='Score', ascending=False).reset_index(drop=True).head(50)

Team        Score
0          Football Club Internazionale Milano S.p.A.  3207.658748
1                             Liverpool Football Club  3202.176534
2                          Real Madrid Club de Fútbol  3173.361520
3                               Arsenal Football Club  3152.742608
4                             Galatasaray Spor Kulübü  3144.887547
5                         Bayer 04 Leverkusen Fußball  3138.549078
6                                   FC Bayern München  3099.327235
7   Eindhovense Voetbalvereniging Philips Sport Ve...  3086.584460
8                   Paris Saint-Germain Football Club  3084.966765
9                          Sporting Clube de Portugal  3077.282646
10                              Futbol Club Barcelona  3057.996747
11                      Manchester City Football Club  3040.352134
12                                          Palmeiras  3029.504110
13                  Atalanta Bergamasca Calcio S.p.a.  3026.243112
14                             Futebol Clube do Porto  3021.420480
15                                Feyenoord Rotterdam  3008.322184
16                             Sport Lisboa e Benfica  2988.062662
17                                   Atlético Mineiro  2968.200427
18                                           Flamengo  2945.090698
19                             Juventus Football Club  2941.336804
20                             Fenerbahçe Spor Kulübü  2920.622648
21                     Club Atlético de Madrid S.A.D.  2917.356546
22                     Newcastle United Football Club  2911.411869
23                           The Celtic Football Club  2911.030810
24                        AO FK Zenit Sankt-Peterburg  2882.789045
25                              Chelsea Football Club  2870.923740
26            Olympiakos Syndesmos Filathlon Peiraios  2865.731289
27                                  Borussia Dortmund  2865.401932
28                          Associazione Calcio Milan  2860.957061
29                      Società Sportiva Lazio S.p.A.  2836.747787
30                               Athletic Club Bilbao  2836.216935
31                                      Internacional  2818.660975
32                                        River Plate  2805.117753
33                     Società Sportiva Calcio Napoli  2795.984474
34                         Futbolniy Klub Dynamo Kyiv  2791.601330
35                      Lille Olympique Sporting Club  2781.512471
36          Club Brugge Koninklijke Voetbalvereniging  2780.997800
37                 Athlitiki Enosi Konstantinoupoleos  2780.930642
38                                FC Shakhtar Donetsk  2773.696717
39                        Royale Union Saint-Gilloise  2771.384357
40                                          São Paulo  2767.945676
41                                           Botafogo  2764.693528
42                                             Grêmio  2762.866832
43                             RasenBallsport Leipzig  2762.132115
44                    Panathinaikos Athlitikos Omilos  2750.338925
45                                       Boca Juniors  2748.676455
46          Verein für Bewegungsspiele Stuttgart 1893  2736.139611
47                             Olympique de Marseille  2730.481403
48                    Tottenham Hotspur Football Club  2729.143868
49                                         Fluminense  2728.572692

In [37]:
pd.DataFrame(list({key: value for key, value in model.elo.rating.items() if key in teams}.items()), columns=['Team', 'Score']).sort_values(by='Score', ascending=False).reset_index(drop=True).head(50)

Team        Score
0          Football Club Internazionale Milano S.p.A.  2014.875952
1                             Liverpool Football Club  2010.585624
2                          Real Madrid Club de Fútbol  1989.058354
3                               Arsenal Football Club  1974.598506
4                             Galatasaray Spor Kulübü  1969.274941
5                         Bayer 04 Leverkusen Fußball  1965.048965
6                                   FC Bayern München  1940.161011
7   Eindhovense Voetbalvereniging Philips Sport Ve...  1932.498733
8                   Paris Saint-Germain Football Club  1931.539597
9                          Sporting Clube de Portugal  1927.024032
10                              Futbol Club Barcelona  1915.971858
11                      Manchester City Football Club  1906.189614
12                                          Palmeiras  1900.321033
13                  Atalanta Bergamasca Calcio S.p.a.  1898.577600
14                             Futebol Clube do Porto  1896.016352
15                                Feyenoord Rotterdam  1889.159886
16                             Sport Lisboa e Benfica  1878.827942
17                                   Atlético Mineiro  1868.998840
18                                           Flamengo  1857.907714
19                             Juventus Football Club  1856.139142
20                             Fenerbahçe Spor Kulübü  1846.536852
21                     Club Atlético de Madrid S.A.D.  1845.046251
22                     Newcastle United Football Club  1842.349006
23                           The Celtic Football Club  1842.176799
24                        AO FK Zenit Sankt-Peterburg  1829.635866
25                              Chelsea Football Club  1824.491882
26            Olympiakos Syndesmos Filathlon Peiraios  1822.262884
27                                  Borussia Dortmund  1822.121944
28                          Associazione Calcio Milan  1820.225009
29                      Società Sportiva Lazio S.p.A.  1810.056044
30                               Athletic Club Bilbao  1809.836051
31                                      Internacional  1802.629679
32                                        River Plate  1797.159164
33                     Società Sportiva Calcio Napoli  1793.511814
34                         Futbolniy Klub Dynamo Kyiv  1791.773068
35                      Lille Olympique Sporting Club  1787.798965
36          Club Brugge Koninklijke Voetbalvereniging  1787.597263
37                 Athlitiki Enosi Konstantinoupoleos  1787.570951
38                                FC Shakhtar Donetsk  1784.746548
39                        Royale Union Saint-Gilloise  1783.847776
40                                          São Paulo  1782.514817
41                                           Botafogo  1781.258084
42                                             Grêmio  1780.553848
43                             RasenBallsport Leipzig  1780.270931
44                    Panathinaikos Athlitikos Omilos  1775.755611
45                                       Boca Juniors  1775.122958
46          Verein für Bewegungsspiele Stuttgart 1893  1770.382060
47                             Olympique de Marseille  1768.259393
48                    Tottenham Hotspur Football Club  1767.759139
49                                         Fluminense  1767.545687